from .Loss import Loss
from .CrossEntropyLoss import CrossEntropyLoss
from .MSELoss import MSELoss
from .L1Loss import L1Loss
from .SwitchLoadBalancingLoss import SwitchLoadBalancingLoss
from .SpecializationLoss import SpecializationLoss
from .ConsistencyLoss import ConsistencyLoss
from .RankCorrelationLoss import RankCorrelationLoss
from .RegretBaseLoss import RegretBaseLoss
from .CrossEntropyRoutingLoss import CrossEntropyRoutingLoss
from .FakeCrossEntropyLoss import FakeCrossEntropyLoss
from .HingeBalancingLoss import HingeBalancingLoss
from .LossWrapper import LossWrapper