type: mlp_moe

router:

  - type: mlp
    model_config: !include router_configs/mlp_router_config.yml
    epochs: [0, 100]
    supervised: true
expert: !include expert_configs/mlp_expert_config.yml
num_experts: 10
k: 1
alternate_epochs: 1