type: rl_moe

router:
  - type: rl
    model_config: !include router_configs/ddqn_config.yml
    epochs: [0, 100]
    supervised: false

expert: !include expert_configs/mlp_expert_config.yml
num_experts: 5
k: 1
alternate_epochs: 1