type: RL
model: DQN

backbone: !include router_configs/resnet_18_router_config.yml
backbone_output_shape: 128

action_assignment_strategy: LinearAssignmentByDiff
reward_function: RegretBasedNew
hidden_dim: 128
buffer_capacity: 61440 # 15 * 4096 - Has to be a multiple of batch_size
batch_size: 1024
gamma: 0.99
epsilon: 0.0
epsilon_min: 0.0
epsilon_decay: 0.99
lr: 0.001
num_of_episodes: 500
save_model: true
save_dir: saved_models/routers
save_name: ddqn
save_period: 10
load_model: false
load_path: saved_models/routers/ddqn.pt
