type: RL
model: DQN

backbone: !include expert_configs/resnet18_expert_config.yml
backbone_output_shape: 128

reward_function: NoaReward
hidden_dim: 128
buffer_capacity: 10000
batch_size: 512
gamma: 0.99
epsilon: 0.0
epsilon_min: 0.0
epsilon_decay: 0.99
lr: 0.001
num_of_episodes: 500
save_model: true
save_dir: saved_models/routers
save_name: mlp
save_period: 10
load_model: false
load_path: saved_models/routers/mlp.pt
