type: RL
model: PPO

backbone: !include expert_configs/resnet18_expert_config.yml
backbone_output_shape: 128

reward_function: NoaReward
hidden_dim: 128
batch_size: 128
gamma: 0.99
policy_clip: 0.2
n_epochs: 10
gae_lambda: 0.95
alpha: 0.003
epsilon: 0.0
epsilon_min: 0.0
epsilon_decay: 0.99
save_model: true
save_dir: saved_models/routers
save_name: ppo
save_period: 10
load_model: false
load_path: saved_models/routers/ppo.pt
