backbone: vit_b_16
backbone_params:
  input_size: None
  output_size: None
  init: xavier_uniform
  dtype: torch.float32
optimizer: adam
optimizer_params:
  lr: 0.001
  weight_decay: 0.0
  momentum: 0.0
  alpha: 0.99
  eps: 1e-06
  lr_decay: 0.0
  betas: [0.9, 0.999]

save_model: true
save_dir: saved_models/routers
save_name: vit_b_16
save_period: 10
load_model: false
load_path: saved_models/routers/vit_b_16.pt


# Path: configs\router_configs\mlp_router_config.yml

