log:
  wandb_project_name: null #cifar10_diversity_loss_vs_cer_loss
  experiment_name: cifar10_2_SGD
  experiment_description: cifar10_2_SGD


dataloader: !include dataloader_configs/cifar10_dataloader_config.yml
scheduler: true
model:
  model: !include model_configs/resnet18_model_config.yml
#  model: !include model_configs/resnet18_and_rl_combined_model_config.yml
  loss: !include loss_configs/moe_loss_config.yml
  optimizer: SGD
  lr: !!float 0.1


metrics:
#    - SuperClassConfusionMatrix
    - MOEConfusionMatrix
#    - ConfusionMatrix
#    -
    - Accuracy
#    - F1
#    - Precision
#    - Recall
#    - pvalue
    - RouterVsRandomAcc
    - ExpertEntropy
    - Consistency
#    - Specialization
    - DeadExperts
    - AccuracyDiff
    - MH

#    - NewSpecialization
seed: 0
epochs: 400

# Path: configs\experiment_configs\cifar10_config.yml
