log:
  wandb_project_name: cifar100_reward_function_experiment
  experiment_name: cifar100_debug_experiment
  experiment_description: cifar 100 reward experiment

# experiment: !include experiment_configs/experiment_config.yml

dataloader: !include dataloader_configs/cifar100_dataloader_config.yml
scheduler: true

model:
  model: !include model_configs/ddqn_model_config.yml
  loss: !include loss_configs/cross_entropy_loss_config.yml
  optimizer: Adam
  lr: !!float 0.001


metrics:
    - SuperClassConfusionMatrix
    - MOEConfusionMatrix
#    - ConfusionMatrix
    - Accuracy
#    - F1
#    - Precision
#    - Recall
#    - pvalue
#    - RouterVsRandomAcc
#    - ExpertEntropy
    - Consistency
    - Specialization
    - DeadExperts


seed: 0
epochs: 1000

# Path: configs\experiment_configs\dummy_config.yml