log:
  wandb_project_name: dummy_project
  experiment_name: dummy_experiment
  experiment_description: dummy_description

# experiment: !include experiment_configs/experiment_config.yml

dataloader: !include dataloader_configs/imagenet_dataloader_config.yml

model:
  model: !include model_configs/moe_model_config.yml
  loss: !include loss_configs/moe_loss_config.yml
  optimizer: Adam
  lr: !!float 3e-4


metrics:
    - Accuracy
    - F1
    - Precision
    - Recall
    - ConfusionMatrix
    - pvalue
    - RouterVsRandomAcc
    - ConfusionMatrix

seed: 0
epochs: 100

# Path: configs\experiment_configs\dummy_config.yml