log:
  wandb_project_name: consistency_loss # hingeLoss_combinations_losses1 #DeepSeek_regret_based_cifar10_parameters_search # linear_balancing_resnet_cifar10_experiment_detached_experts
  experiment_name: dummy_experiment
  experiment_description: dummy_description


dataloader: !include dataloader_configs/cifar100_dataloader_config.yml
scheduler: true
model:
  model: !include model_configs/resnet18_model_config.yml
  loss: !include loss_configs/moe_loss_config.yml
  optimizer: Adam
  lr: !!float 0.001


metrics:
    - SuperClassConfusionMatrix
    - MOEConfusionMatrix
#    - ConfusionMatrix
    - Accuracy
#    - F1
#    - Precision
#    - Recall
#    - pvalue
#    - RouterVsRandomAcc
#    - ExpertEntropy
    - Consistency
    - Specialization
    - DeadExperts

#    - NewSpecialization
seed: 0
epochs: 200

# Path: configs\experiment_configs\cifar10_config.yml