base_config: cifar10_config.yml

changes:
  - key:
      model:
        loss:
          MixtureOfExpertLoss:
            losses
    options:
      - - !include loss_configs/cross_entropy_loss_config.yml
        - !include loss_configs/regret_base_loss_config.yml
      - - !include loss_configs/cross_entropy_loss_config.yml
        - !include loss_configs/rank_correlation_loss_config.yml
      - - !include loss_configs/cross_entropy_loss_config.yml
        - !include loss_configs/switch_load_balancing_loss_config.yml
      - - !include loss_configs/cross_entropy_loss_config.yml
        - !include loss_configs/consistency_loss_config.yml
        - !include loss_configs/specialization_loss_config.yml


  - key:
      model:
        loss:
          MixtureOfExpertLoss:
            weights
    options:
      - [1., 0.1, 0.1]