base_config: ddqn_cifar10_config.yml

changes:
  - key:
      model:
        model:
          router:
            model_config:
              reward_function
    options:
#      - SpecializationAndConsistency
        - RegretBasedNew
        - CrossEntropyRouting
      #- SpearmanCorrelation
        #- RegretBased
        #- Expertise
        #- ProposalSpecializationAndConsistency
  - key:
      model:
        model:
          router:
            model_config:
                action_assignment_strategy
    options:
#      - LinearAssignmentByDiff
      - LinearAssignmentWithCapacity
#      - BaseLinearAssignment
#      - none

  - key:
      scheduler
    options:
#      - false
      - true

  - key:
      model:
        model:
          alternate
    options:
      - 0
      - 2
      - 5
