dataset: cifar10
batch_size: 16
transform: true
transforms:
  augmentations: !include augmentation_configs/all_augmentations_config.yml
  ToTensor: null
  Resize:
    size: 32
    antialias: true
  Normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]
    inplace: true

shuffle: true
num_workers: 1

# Path: configs\dataloader_configs\cifar10_config.yml
    