dataset: cifar10
batch_size: 512
transform: true
transforms:
  ToPILImage: null

  augmentations: !include augmentation_configs/all_augmentations_config.yml
#  CenterCrop:
#    size: 24
  Resize:
    size: 32
    antialias: true
  ToTensor: null
#  GaussianBlur:
#      kernel_size : [3, 7]
#      sigma: [1.1, 2.2]
  Normalize:
    mean: [0.4914, 0.4822, 0.4465]
    std: [0.2023, 0.1994, 0.2010]

shuffle: true
num_workers: 4

# Path: configs\dataloader_configs\cifar10_config.yml
    