dataset: mnist
batch_size: 16
transform: true
transforms:
#  augmentations: !include augmentation_configs\all_augmentations_config.yml
  ToTensor: null
  Normalize:
      mean: [0.1307]
      std: [0.3081]

shuffle: true
num_workers: 4

# Path: configs\dataloader_configs\mnist_config.yml
